---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  # yamllint .
  # yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
  yamllint -c molecule/ubuntu2004/custom-yaml-lint.yml .
  ansible-lint
  flake8

platforms:
  - name: githubactions-ansible-role-molecule-archlinux
    # image: archlinux:latest #https://hub.docker.com/_/archlinux
    image: archlinux:base-devel-20210328.0.18194 #https://hub.docker.com/_/archlinux


provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: archlinux

verifier:
  name: testinfra
  directory: ../default/tests
