---
dependency:
  name: galaxy

driver:
  name: docker

# lint:
#   name: yamllint
#   options:
#     config-data:
#       line-length: disable

# https://molecule.readthedocs.io/en/latest/configuration.html
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
#   flake8

# https://molecule.readthedocs.io/en/latest/configuration.html
lint: |
  set -e
  # yamllint .
  # yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
  yamllint -c custom-yaml-lint.yml .
  ansible-lint
  flake8


# lint:
#   - |
#     set -e
#     yamllint .
#     ansible-lint
#     flake8
#   - name: yamllint
#       options:
#         config-file: molecule/ubuntu2004/yaml-lint.yml

# lint:
#   - name: yamllint
#     options:
#       config-file: molecule/ubuntu2004/yaml-lint.yml
#   - |
#     set -e
#     yamllint .
#     ansible-lint
#     flake8

platforms:
  - name: ansible_role_ubuntu_2004
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: ubuntu2004

verifier:
  name: testinfra
  directory: ../default/tests
